name: Deploy to Hugging Face

on:
  push:
    branches:
      - main  # Triggers on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ubuntu runner

    steps:
    - uses: actions/checkout@v2  # Check out the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'  # Your specific Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Authenticate with Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Use the HF token from GitHub secrets
      run: |
        huggingface-cli login $HF_TOKEN

    - name: Push to Hugging Face
      run: |
        git config --global user.email "nlynge21@student.aau.dk"  
        git config --global user.name "NicklasMadsen"  
        git remote add huggingface https://huggingface.co/spaces/NicklasMadsen/af.git || true  # Add remote if it doesn't exist
        git push huggingface main
