name: Hugging Push

on:
  push:
    branches:
      - main

jobs:
  sync_to_huggingface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

      - name: Hugging Face Sync
        uses: backendcloud/hugging-push@v0.2.3
        with:
          huggingface_repo: NicklasMadsen/af  # Assuming 'af' is the space name in Hugging Face
          hf_token: ${{ secrets.HF_TOKEN }}  # Hugging Face access token stored in GitHub secrets
          repo_type: space  # Since you're pushing to a space, not a model
          space_sdk: streamlit  # Assuming you're using Streamlit; replace if using another SDK
          private: false  # Set this according to your privacy preference on Hugging Face
