name: Hugging Face Sync

on:
  push:
    branches:
      - main

jobs:
  sync_to_huggingface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hugging Face Sync
        uses: JacobLinCool/huggingface-sync@v1.0.0
        with:
          user: NicklasMadsen
          space: af
          token: ${{ secrets.HF_TOKEN }}  # Hugging Face access token stored in GitHub secrets
          github: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided GitHub Actions token
